madetech/site

src/all.scss, src/components/Contentful/HubSpotArea.js, src/components/Contentful/HubSpotForm.js, src/components/Contentful/_contentful_hub_spot_form.scss, src/components/Contentful/index.js, src/components/Layout/Scripts.js, src/templates/ContentfulPage/index.js
Still a WIP.
Struggling to see how to extrapolate the Hubspot form IDs when they are required in the hubspot js script rather than being the anchor id for the div/form like Convertflow.
=> [WIP] Hubspot insights form

bin/deploy-preview.js, circle.yml, gatsby-config.js, preview/.gitignore, preview/data/contentful.js, preview/next.config.js, preview/package-lock.json, preview/package.json, preview/pages/preview.js, src/components/Layout/Meta.js, src/components/Layout/index.js
We add a preview application for Contentful that will enable live previews of content changes. Currently only built to work in development mode, we will later replace the existing preview deployment on Heroku with this application.
Currently any changes in Contentful admin take 30-40 seconds to reach the preview environment. This change makes changes immediate as we fetch the content on page load from Contentful rather than requiring a build step on CircleCI.
=> Add contentful preview app

package-lock.json, package.json, src/components/Contentful/_contentful_card.scss, src/components/Layout/index.js, src/components/Post/Meta.js, src/components/Post/Tags.js, src/components/Post/_post_meta.scss, src/components/Post/_post_tags.scss, src/components/PostList/Item.js, src/components/PostList/_post_list.scss, src/components/PostList/_post_list_intro.scss, src/components/PostList/_post_list_item.scss, src/templates/PostListPage/index.js
We've updated @madetech/frontend to use smaller font sizes and less spacing. This update to the site builds on these changes.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> Reducing overall font sizes and spacing

src/components/JobsBoard/index.js
remove code that appends to the body in the head (causes race condition where the body is not loaded yet)
=> remove appendChild from widget script

src/templates/PostListPage/index.js
- Consolidate "Cloud Automation" into "DevOps" 
- Remove "Upskilling & Training"
- Introduce "Employers as Educators" and "User-Centred Technology" as these are marketing themes
- Introduce "Academy" and "Diversity and Inclusion" to get more visibility on this content
We want our topics to be current and in line with marketing activities.
=> Update blog index to link to more current topics and categories

package-lock.json, src/components/Contentful/Grid.js, src/components/Contentful/index.js, src/templates/ContentfulPage/index.js
Added layout property to GridContainer to allow for fluid containers
=> Added layout property to GridContainer

src/components/Contentful/_contentful_fonts.scss, src/components/Contentful/_contentful_grid.scss, src/components/Contentful/_contentful_new_design.scss
WHAT: Added stylings to the pull quote
WHY: So it matches up with the designs provided
=> Add blockquote styling

src/components/Contentful/_contentful_new_design.scss, src/components/Contentful/_contentful_settings.scss
WHAT: Changed padding values for desktop, tablet and mobile.
WHY: To meet the designs
BEFORE:
AFTER:
=> Add padding to grid components

package-lock.json, preview/yarn.lock
- Update `package-lock.json` with `npm audit fix`
- Update `preview/yarn.lock` with `rm -rf node_modules/ && rm yarn.lock && yarn`
To fix vulnerable packages that have since been patched.
=> Update vulnerable deps

package-lock.json, package.json
- Update gatsby
- Update gatsby-plugin-feed
- Update gatsby-plugin-manifest
- Update gatsby-plugin-offline
- Update gatsby-plugin-react-helmet
- Update gatsby-plugin-sass
- Update gatsby-source-contentful
- Update gatsby-source-wordpress
Continuous modernisation and improvement includes reducing the age of technology. Keeping to latest version of gatsby should be more secure, and reduce upgrade pains in future/
=> Update gatsby and related deps

package-lock.json, package.json, preview/package.json, preview/yarn.lock
Update `react`, `react-dom` and `react-helmet`.
Continuous modernisation.
=> Update react to 16.9.0 and related deps

package-lock.json, package.json, preview/package.json, preview/yarn.lock
- Bump universal-cookie dep
- Update dotenv
- Update query-string
- Update disqus-react
- Update @madetech/frontend
- Update @contentful/rich-text-html-renderer
Continued modernisation.
=> Update other deps

package-lock.json, package.json, preview/package.json, preview/yarn.lock
Update all developer dependencies.
Continued modernisation.
=> Update dev deps

src/components/Contentful/Grid.js, src/components/Contentful/_contentful_new_design.scss, src/components/Contentful/_contentful_settings.scss, src/components/Contentful/index.js, src/templates/ContentfulPage/index.js
I want to add a background image to a grid.
So I can put overlay an image with text from a grid component.
=> Add background image property to grid

src/components/Contentful/Highlight.js, src/components/Contentful/_contentful_highlight.scss, src/components/Contentful/index.js, src/templates/ContentfulPage/index.js
**What:**
Add functionality to contentful highlights to be able to render an author underneath their body
**Why**
So that highlights can contain quotes/customer testimonials with an attribution
=> Highlight authors

src/components/Contentful/_contentful_fonts.scss, src/components/Contentful/_contentful_new_design.scss, src/helpers/threeSpaceToLineBreak.js
Updated some styles to fix font-wrap, padding, and spacing issues
=> Updated fonts, padding, spacing

src/components/Contentful/Grid.js, src/components/Contentful/Highlight.js, src/components/Contentful/InlineImages.js, src/components/Contentful/Jumbotron.js, src/components/Contentful/Prose.js, src/components/Contentful/_contentful_fonts.scss, src/components/Contentful/_contentful_highlight.scss, src/components/Contentful/_contentful_new_design.scss, src/components/Contentful/_contentful_settings.scss, src/components/Contentful/_custom_styles.scss, src/components/Contentful/index.js, src/helpers/threeSpaceToLineBreak.js, src/templates/ContentfulPage/index.js
- Add column/offset options for all the various bootstrap breakpoints
- Adjust various styles to make use of the new options
Doing this via overrides in the CSS was becoming hard to manage
=> Column sizes for all breakpoints

src/components/Contentful/Grid.js, src/components/Contentful/_contentful_fonts.scss, src/components/Contentful/_contentful_new_design.scss, src/helpers/threeHyphenToSoftHyphen.js
Added a helper to allow for soft-hyphens to be inserted.
Auto hyphenation in CSS doesn't do a very good job of choosing where to put the hyphen.
=> Added helper to allow for soft hypens to be inserted

src/components/Contentful/_contentful_settings.scss, src/components/Contentful/_custom_styles.scss, src/helpers/documentToHtmlString.js
Add images to page content via the rich content editor.
So that we can add images in our content easily.
=> Add inline images

src/components/Contentful/Hero.js, src/components/Contentful/index.js, src/components/Contentful/sass/abstracts/_variables.scss, src/components/Contentful/sass/components/_contentful_hero.scss, src/templates/ContentfulPage/index.js
Add ability to have breadcrumb links using JSON field in contentful hero
=> Add breadcrumb links

src/components/Contentful/Hero.js
**WHAT**
Made changes to allow key to be added to react fragment
**WHY**
To stop React from getting upset
=> Fix breadcrumb react error

src/components/Contentful/Highlight.js, src/components/Contentful/index.js, src/templates/ContentfulPage/index.js
Add column widths for all breakpoints to the highlight component
We want to be able to cover more of the screen on smaller devices
=> Added column widths for all breakpoints to highlight component

src/components/Contentful/sass/sections/_shared.scss, src/components/Layout/index.js
Updated headers to match requested design
=> Updated headers

package-lock.json, package.json, src/components/Contentful/Grid.js, src/components/Contentful/Tweet.js, src/templates/ContentfulPage/index.js
Add tweet type
We want to be able to add embedded tweets easily via contentful
=> Add tweet type

package-lock.json, package.json
**WHAT**
Updated the frontend package version
**WHY**
It contains fixes for the fonts and resized social icons
=> Updated the frontend package version to 5.9.3

src/components/Contentful/HeaderImages.js, src/components/Contentful/index.js, src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/contentful_header_images.scss, src/templates/ContentfulPage/index.js
Add new header images component to contentful
So that content editors can update the header images in the CMS
=> Add header images component to contentful

src/components/Contentful/Grid.js, src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/_contentful_grid.scss, src/components/Contentful/sass/sections/_contact.scss, src/templates/ContentfulPage/index.js
Styling to handle contact page
=> Contact us page

src/templates/ContentfulPage/index.js
Fixed issue where careers page jobs board was not the correct width
=> Added graphql to query jobsboard properly

src/components/Contentful/sass/sections/_contact.scss
Final bits of styling for get in touch page
=> Get in touch page

src/components/Contentful/sass/base/_typography.scss, src/components/Contentful/sass/components/_new_design_overrides.scss
**What**
A couple of minor style improvements
**Why**
The bullet point positioning was a bit weird and the desktop text for blockquotes was a bit too big
=> Styling improvements

src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/sections/_contact_component.scss
**WHAT**
Added CSS to style Get In Touch component
Dark version:
Light version:
=> Get in touch component

src/components/Contentful/sass/sections/_contact_component.scss
Fixed issues with mobile padding
=> Added mobile and tablet font sizing/spacing

src/components/Contentful/Grid.js, src/components/Contentful/Prose.js, src/components/Contentful/index.js, src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/_contentful_prose.scss, src/components/Contentful/sass/components/_new_design_overrides.scss, src/components/Contentful/sass/sections/_partners.scss, src/templates/ContentfulPage/index.js
**WHAT**
Added support for screen reader text in prose - hides the body of the prose 
Added styles for AWS partner detail page
=> Partner detail

package-lock.json, package.json, src/components/Layout/index.js
Header and Sitemap are now using the updated Books URL.
=> Update header and footer to include new Books URL

src/components/Contentful/Hero.js
Added an if statement to check for existence of imageHeader in Contentful query. To see if lack of check was cause of build error.
=> Add if statement to check for imageHeader

src/components/Contentful/Hero.js, src/components/Contentful/sass/components/_contentful_hero.scss
Changing some styling and responsiveness based on Kalle's feedback.
=> New Header Adjustments

src/components/Contentful/Hero.js, src/templates/ContentfulPage/index.js
Adding lazy loading to improve user experience when loading the website on a slow network. Adding a query for a lower quality image that loads first.
=> adding lazy loading to have a place holder for hero image

src/components/Contentful/sass/abstracts/_variables.scss, src/components/Contentful/sass/components/_contentful_hero.scss
Making header title and header paragraph responsive
=> Adding text resizing to the header

src/components/Contentful/Hero.js, src/components/Contentful/index.js, src/components/Contentful/sass/components/_contentful_hero.scss, src/templates/ContentfulPage/index.js
Adding an option of grey header background
=> Header background

src/components/Contentful/sass/components/_contentful_hero.scss
Adding spacing between the header text and image, changing sizes
=> Added some improvements to the header based on Kalle's design

src/components/Contentful/sass/components/_contentful_hero.scss
=> Revert "Added some improvements to the header based on Kalle's design"

src/components/Contentful/Hero.js
=> Revert "Fixing mistakes during the previous merge conflict"

src/components/Contentful/Hero.js, src/components/Contentful/index.js, src/components/Contentful/sass/components/_contentful_hero.scss, src/templates/ContentfulPage/index.js
=> Revert "Header background"

src/components/Contentful/Hero.js, src/components/Contentful/index.js, src/components/Contentful/sass/components/_contentful_hero.scss, src/templates/ContentfulPage/index.js
=> Revert "Revert "Header background""

src/components/Contentful/Hero.js, src/components/Contentful/index.js, src/components/Contentful/sass/components/_contentful_hero.scss, src/components/Contentful/sass/components/_new_design_overrides.scss, src/templates/ContentfulPage/index.js
Adding a possibility for header links. The field is already added on Contentful as part of Hero component. 
The links still need to be styled better and tested with more elements/resizing.
=> Header links

src/components/Contentful/Grid.js, src/components/Contentful/index.js, src/templates/ContentfulPage/index.js
Making sure we actually parse the HTML given to Image link!!
From: 
To:
=> Image link

src/components/Contentful/ImageLink.js, src/templates/ContentfulPage/index.js
Adding column widths so that users can change the sizing of ImageLinks in contentful.
=> Adding column widths and offsets to allow better layouts in the grid

src/components/Contentful/sass/components/_contentful_imagelink.scss
Changing font size for text in imageLink component, to match Kalle's design.
=> Preprodimagelink

src/components/Contentful/Grid.js, src/components/Contentful/Hero.js, src/components/Contentful/sass/components/_contentful_hero.scss, src/templates/ContentfulPage/index.js
Adds Link Title field to Grid. 
Adds styling for header links section 
Fixes div shadow issues in Firefox.
=> Header links branch

preview/public/index.html, src/components/Contentful/Grid.js, src/components/Contentful/Hero.js, src/components/Contentful/InlineImages.js, src/components/Contentful/index.js, src/components/Contentful/sass/components/_contentful_hero.scss, src/components/Contentful/sass/components/_contentful_inline_images.scss, src/templates/ContentfulPage/index.js
Merging master into Preview in order to make Contentful previews work
=> Putting new content to preview branch

src/components/Contentful/Carousel.js, src/components/Contentful/index.js, src/templates/ContentfulPage/index.js
Merging into master so that no one's code breaks because of the Contentful carousel.
=> Adding query for carousel and adding a new minimal carousel component

preview/src/data/contentful.js
Small changes that make the preview site work locally - it's still not perfect (missing the coloured shadow for the hero image - but this seems to only be an issue for me....) but would be good to see if this will at least un-break the preview site.
=> Previewfix

preview/package-lock.json, src/components/Layout/index.js
CookiConset import was generating warnings up compilation because it was never used.
=> removed cookieConsent import

src/components/Contentful/Hero.js, src/components/Contentful/index.js
Allows images to be displayed higher (slightly overlaying over the component above) if the overlay option is selected in Contentful
=> Adding implementation of overlay option to Inline images

gatsby-node.js, package.json, src/components/Contentful/Hero.js, src/components/Contentful/sass/components/_contentful_hero.scss
Using Hero component instead of creating a new one.
Splitting some of hero scss into frontend.
Will not work until https://github.com/madetech/frontend/pull/9 is committed and the package is published. 
Please do not merge until then.
=> Refactoring Hero

src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/_new_design_overrides.scss, src/components/Contentful/sass/sections/_case_study_1.scss, src/components/Contentful/sass/sections/_case_study_2.scss
Adding custom classes for case studies styling
Before:
After:
=> Case study custom classes

src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/sections/_frameworks.scss
Added custom styling to mainly improve the way the _Crown Commercial Service Supplier_ logo looked and also to make the page more response.
From
To
=> Frameworks

src/components/Contentful/sass/components/_contentful_inline_images.scss
=> Revert "prevented the inline overlay photos from going over previous sections…"

src/components/Contentful/sass/sections/_case_study_1.scss, src/components/Contentful/sass/sections/_shared.scss
Removed the right padding for the image in case_study_1 and also changed its the left and right margins in order to align properly with other sections of the page.
Before:
After:
=> Talk to us

src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/_contentful_card.scss, src/components/Contentful/sass/components/_contentful_grid.scss, src/components/Contentful/sass/components/_contentful_hero.scss, src/components/Contentful/sass/components/_contentful_jumbotron.scss, src/components/Contentful/sass/components/_contentful_prose.scss, src/components/Contentful/sass/components/_new_design_overrides.scss, src/components/Marketing/_hiring.scss, src/components/Post/_post.scss, src/components/PostList/_post_list_item.scss
Fixing these issues:
https://trello.com/c/hpG12GTK/157-general-push-down-underline-in-links
https://trello.com/c/Mf0XOp4Y/158-general-dark-copy-should-be-333
https://trello.com/c/5yLt1iJo/160-partners-overview-looks-like-were-squeezing-the-copy-here
=> Design fixes

src/components/Contentful/sass/sections/_case_study_1.scss, src/components/Contentful/sass/sections/_contact_component.scss, src/components/Contentful/sass/sections/_shared.scss
Changed the position of the image in case-study-1 section to reduce the overlay.
From:
To:
Removed left margin of case-study-1 section to align it properly on mobile view.
From:
To:
Changed the styling of the contact_component so the small images align properly and changed the big image in this component so it stays for longer when the screen is resized.
From:
To:
=> Case study 1

src/components/Contentful/sass/sections/_case_study_1.scss, src/components/Contentful/sass/sections/_case_study_2.scss
Further changes to case-study-1 section for smaller view ports. Also some work done to case-study-2 section to make the image fit the section properly.
=> Case study 2

src/components/Contentful/sass/sections/_case_study_2.scss
Changed case-study-2 section to place the image in the center.
From:
To:
=> case-study-2

src/components/Contentful/Hero.js, src/components/Contentful/sass/base/_typography.scss, src/components/Contentful/sass/components/_contentful_hero.scss, src/components/Contentful/sass/components/_new_design_overrides.scss, src/components/Contentful/sass/sections/_case_study_moj.scss, src/components/Contentful/sass/sections/_shared.scss, src/templates/ContentfulPage/index.js
Mainly minor styling tweaks for the /case-study page and making it more responsive.
Also, this is the only hero without a coloured shadow. 
Initially, I put a low quality background image behind the Hero image, but it made the picture look fuzzy, so got rid of it:
From on left, To on right - very subtle but you can see the left is a bit fuzzy
From --> To
=> Case study

src/components/Contentful/sass/sections/_our_services.scss
Added styling to implement the new design for desktop version. Work still in progress for smaller view ports.
From:
To:
From:
To:
=> Services overview new

src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/_new_design_overrides.scss, src/components/Contentful/sass/sections/_academy.scss, src/components/Contentful/sass/sections/_our_purpose.scss
- Made green a 'Style' option for grids now, which looks like this:
- Lots of styling mainly for the Academy page. e.g
From:
To:
From:
To:
=> Academy page

package-lock.json, package.json, src/all.scss, src/components/Contentful/Carousel.js, src/components/Contentful/index.js, src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/_contentful_carousel.scss, src/templates/ContentfulPage/index.js, test/setup.js
So this uses the [react-slick component](https://github.com/akiran/react-slick).
Right now it can only do images, and only one image at a time, so it can be used for the [case study page](https://app.zeplin.io/project/5de03234a892f77c201cf303/screen/5de033db1d3db37bea960bda), but hopefully it will work with prose for the [academy page](https://app.zeplin.io/project/5de03234a892f77c201cf303/screen/5dfa03dbfff3c717ba6191d8) too.
Initially when I started using the package, the tests failed, but then [I just had to add something](https://github.com/akiran/react-slick/issues/742) to test/setup.js.
In this PR, I've added the component and added some styling to match our design. It is sort of responsive too, but might change if Kalle wants.
It's available on /test-dummy at the bottom.
Desktop: …
=> New carousel

src/components/Contentful/InlineImages.js, src/components/Contentful/sass/sections/_academy.scss, src/components/Layout/index.js
Possibly my last PR for g2m from my understanding... 😭 
This is mainly addressing feedback from Kalle on the Academy page and also cleaning up unused imports/variables.
=> Academy fixes

preview/package.json, preview/yarn.lock
Add react hamburger dependency to preview app.
So it compiles :)
=> Add hamburger dependency to preview app

src/components/Layout/index.js
Add Case Study page links to the sitemap
=> Going Live with Case Study pages

gatsby-config.js, package.json
Added a new npm package for a gatsby sitemap.xml generator
Existing sitemap.xml is out of date
How to submit sitemap to google 
https://support.google.com/webmasters/answer/183668?hl=en)
=> Added a plug in to create a sitemap.xml

src/components/Layout/index.js
Fixed a typo
Misson was spelled wrong
=> Fixed type in spelling of mission

config/nginx.conf.erb
Added 1 static rewrite rule
We want to test one rewrite rule works
=> Add static rewrite test

config/nginx.conf.erb
Added a new location rewrite block
Server rewrite didn't work
=> Add static rewrite test for staging use location

config/nginx.conf.erb
Add redirects for old indexed links to new pages
Google is still indexing old links from the Rails app which we want to decommission.
=> Add redirects for old indexed links to new pages

package-lock.json, package.json
- Update @madetech/frontend to v5.11.0.
Footer links for social profiles were using old URLs from our legacy site (tracking purposes). I've now fixed these in @madetech/frontend and updated here.
=> Fix social links in footer

src/components/Contentful/Carousel.js, src/components/Contentful/MobileMenu.js, src/helpers/documentToHtmlString.js, src/helpers/documentToHtmlString.test.js
=> Run dev warnings

src/components/Contentful/sass/components/_contentful_hero.scss, src/components/Contentful/sass/sections/_case_study_1.scss
Added margin changes to keep the image flush above the underneath panel
=> Laptop hero image

.gitignore, src/components/BookPreview/index.js
Hard coded the values to display the latest ebook for the moment until we create a swappable contentful component
=> add the MLA component to end of blog pages

src/components/Contentful/Highlight.js, src/components/Contentful/index.js, src/components/Contentful/sass/components/_contentful_grid.scss, src/components/Contentful/sass/components/_contentful_highlight.scss, src/templates/ContentfulPage/index.js
'Our Approach' box is now overlapped by 'David Lewis Highlight'
=> Highlight on Services>Digital overlapping grid element above

src/components/Contentful/EbookPreview.js, src/components/Contentful/Grid.js, src/templates/ContentfulPage/index.js
Added the correct `Grid` attributes for the contentful type we are using
=> Ebook grid

src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/sections/_ebooks.scss
Currently viewable at /resources/books/test
=> New book library page

src/components/Contentful/sass/sections/_case_studies.scss
Transparent background for all cards without a photo.
Also, resized and repositioned a booklet image
=> Transparent backgrounds

src/components/Contentful/DripForm.js, src/components/Contentful/DripForm.test.js, src/components/Contentful/sass/components/_contentful_drip_form.scss
Makes changes based on feedback from Laura: https://trello.com/c/Tzbm33yK/360-embedding-drip-forms#comment-5ef4819e53b4480b6610128d
- Moves hardcoded privacy policy below input fields
- Adjusts the width of the form
=> Make feedback changes to Drip Form component

src/components/Contentful/sass/sections/_case_studies.scss
Allowing case studies page to be masonry style
=> Case studies columns

config/nginx.conf.erb, src/components/Contentful/sass/_new_design.scss, src/components/Contentful/sass/components/_contentful_hero.scss, src/components/Contentful/sass/components/_new_design_overrides.scss
=> Revert "Fix/390 build 404 page"
