madetech/site

src/components/Post/_post.scss

- Add support for enlarged quotes (opt-in in WP admin)
Small quote before change:
Small quote after:
Quotes with a large amount of content shouldn’t have a huge font size as they become hard to read, especially on smaller screens.
This enables authors within WP to opt into enlarged quotes, and default quotes are now smaller.

Improve block quote styling for Wordpress quotes

---

src/components/Marketing/Hiring.js

Because this snippet isn't controlled by a CMS, it's hard to keep it up to date.

Update text in job banner to not include specific roles

---

.gitignore
preview/src/App.js
src/all.scss
src/components/Contentful/contentful_fonts.scss
src/components/Layout/index.js
src/templates/ContentfulPage/index.js

The new website design for g2m will be using different styles to the current Made Tech site. In order to have pages with the new design sit alongside the old, we want to add a feature flag at the page level.
In this PR we will add feature flags to the page component to allow pages to have different styles, and we will add some new feature-flagged font styles.

Add feature flags to page component

---

src/components/Contentful/Grid.js

Update the GridProse component to check for an imageStyle of "after" so that we can postion an image after the text.
We want to be able to position images below text in a GridProse component.

Update GridProse to allow for bottom-positioned images

---

package-lock.json
package.json
src/components/Contentful/Hero.js
src/helpers/threeSpaceToLineBreak.js

Add a helper to convert groups of 3 spaces to line-breaks.
I want to be able to add line breaks in html headers in Contentful.
I want the title "Legacy Transformation Services" to have line-breaks so that the header html looks like `<h1>Legacy<br/>Transformation<br/>Services</h1>`
To add a header with line-breaks, I need to add groups of 3 spaces to the title. So the title I would add to Contentful would be "Legacy   Transformation   Services".

Add helper to convert 3 consecutive spaces to line-breaks

---

package-lock.json
package.json

I've added `lint-changed` and `husky` to add pre-commit hooks for running prettier. This means when you commit, prettier will run on changed files only. It will then leave changes staged, that you need to fold (`git commit --amend`) into your committed changes.
So that we can keep style in line as we go, rather than requiring changes requested in #29.

Install lint-staged and husky for pre-commit formatting

---

src/components/Contentful/_contentful_new_design.scss

Added margin to work in conjunction with contentful changes (h3 > h2) to address this ticket:
https://trello.com/c/6GeBCPpx/64-header-too-small

Added bottom margin for h2

---

src/components/Contentful/_contentful_new_design.scss
src/components/Contentful/_custom_styles.scss

Added custom class for data process chart and moved import for custom classes
I moved the import for custom styles to the bottom of the new design file, because the design should specify what these things look like but I think we should be able to override it using custom classes in Contentful.

CSS for data services process chart

---

src/components/Contentful/Grid.js

Remove gatsbys fixed width from img url
Fixed width was causing fuzzy images

Remove gatsbys fixed width from img url as was causing fuzzy images

---

gatsby-node.js

Update the page-data version number in the webpack loader
So the loader pulls the correct (non-cached) version down

Update the page-data version number in the webpack loader

---

src/components/Contentful/sass/abstracts/_variables.scss
src/components/Contentful/sass/base/_typography.scss
src/helpers/threeHyphenToSoftHyphen.js
src/helpers/threeSpaceToLineBreak.js

Fixed the soft-hyphen insertion function.
Previously, the function was turning each three-hyphen group into a it's own string which was causing the browser to break at the newly created string boundary. For example:
`<h1>Techno---logy</h1>`
was being output as
```
<h1>
"Techno"
"&shy;"
"logy"
</h1>
```
rather than
```
<h1>
"Techno&shy;logy"
</h1>
```

Fixed the soft-hyphen insertion function

---

src/components/Contentful/Hero.js
src/components/Contentful/index.js
src/components/Contentful/sass/abstracts/_variables.scss
src/components/Contentful/sass/base/_typography.scss
src/components/Contentful/sass/components/_contentful_hero.scss
src/components/Contentful/sass/sections/_contact.scss
src/components/Contentful/sass/sections/_our_services.scss
src/components/Contentful/sass/sections/_sectors.scss
src/templates/ContentfulPage/index.js

**WHAT**
Removed specific hero styling from various page styles
Added ability to set hero text colour to green, black or white via contentful
Added small text option for hero text to contentful
**WHY**
To open up more aspects of the hero appearance to editors on Contentful and simplify CSS

Made hero design more controllable via contentful

---

src/components/BookPreview/index.js
src/components/Contentful/sass/components/_contentful_grid.scss
src/templates/PostPage/index.js

Adds a new book preview to the footer of blog post pages linking to the download form.
This is a static component, as in, it uses the same component used for Contentful content, with a static hash within it for the content for the book preview itself.

Add static BookPreview component to footer of Blog post

---

package-lock.json
package.json
preview/package.json
preview/yarn.lock
src/components/Post/index.js

**Why?**
The Disqus block takes up some quite valuable screen estate at the bottom of blog posts which we could better use with call to actions for other items we're trying to promote, such a a new book. Looking over the most recent blog posts, there are zero comments on each, so not sure we're getting any engagement from having it either.

Remove Disqus from blog post pages

---

src/components/Contentful/Grid.js
src/templates/ContentfulPage/index.js

**WHAT**
Added support for the **Image Url** field on the prose model
**WHY**
There was a desire to have the images next to our office addresses on the get in touch page link out to google maps. With this we now have the ability to have the images that are attached to prose be wrapped in a link.

Added ability to have URLs attached to images in prose

---

src/components/Contentful/Grid.js
src/components/Contentful/Hero.js
src/components/Contentful/Highlight.js
src/components/Contentful/Jumbotron.js
src/components/Contentful/index.js
src/components/Contentful/sass/components/_contentful_hero.scss
src/templates/ContentfulPage/index.js

why?
Created headerLinks to enable linking to different sections of the page. In order to do this it was crucial to query the IDs of the components being referenced. Headerlinks contain references to different component types, therefore each component needs to be queried separately using GraphQL. 
Currently headerLinks make it possible to link to Grid, Jumbotron and Highlight. In Contentful only those components are allowed to be referenced. For now.

Header links

---

src/components/Contentful/Hero.js
src/components/Contentful/sass/components/_contentful_hero.scss
src/templates/ContentfulPage/index.js

Pulling page info from Contentful using graphql so that links in the header could reference different pages.
Right now all jumbotron, highlight, page and grid should be referenced at least once in Contentful or these errors appear:
**Fragment cannot be spread here as objects of type "ContentfulGridContentfulJumbotronUnion" can never be of type "ContentfulHighlight"**
Adjusting styling of links based on the type of link.

Changing code to accept links to different pages and changing styling

---

preview/.gitignore
src/components/Contentful/Grid.js
src/components/Contentful/Hero.js
src/components/Contentful/Highlight.js
src/components/Contentful/InlineImages.js
src/components/Contentful/Jumbotron.js

Adding a space to the <a> tag as a content and adding href to to <a> tags.
There is still 1 warning to address:
Also changing ${overlayClassName} to ${overlay} as it is a correct one to use.

Fixing build warnings

---

src/components/Contentful/ImageLink.js
src/components/Contentful/sass/components/_contentful_imagelink.scss

Fixing the sectors/ImageLink styling according to Rory and Kalle's feedback.
- Got rid of width styling for image
- We had a container inside a container, which mean we had 20px padding on top of 20px padding, which ruinied things, so just got rid of the container in ImageLink.
From: 
To:

Minorstyling

---

preview/src/data/contentful.js
src/templates/ContentfulPage/index.js

Two parts: 
1) Renamed imagelink on contentful to imageLink, which meant the if statement wasn't necessary anymore.
2) Getting headerLinks to render on the preview site. The main issue was that the Hero component wasn't receiving the correct info to render the HeaderLink, because of some strange nesting and also components weren't being passed down their id for the references needed.
What we have on the normal site and what works:
What was being passed as "headerLinks" in the preview site:
- All needed info is under another layer, inside 'fields'
- Also 'reference' is 'undefined' even though the id is actually there inside 'sys'
Seems to be working now 🎉

Fixing HeaderLinks in preview

---

src/templates/ContentfulPage/index.js

Wrapping Hero headerLinks references inside a Node means that inside of the Contentful content model you don't necessarily have to have included references to all the components that can be referenced. 
Without the Node wrapper, when GraphQL pulls the data from the content model itexpects to have at least one instance for every reference-able component

Wrapped GraphQL headerLinks references query in a Node

---

src/components/Contentful/Grid.js
src/components/Contentful/sass/components/_new_design_overrides.scss
src/components/Contentful/sass/sections/_our_services.scss

Had to go into Grid.js and hide the <a> tag which contains the anchor reference for Header Links as it otherwise shows up on the display. The tag has to have something in it otherwise a warning is generated when the app runs. 
The green box on the left is the <a> tag:
Without updated styling:
With updated styling applied:

￼￼￼￼Services styling update

---

src/components/Contentful/sass/components/_new_design_overrides.scss
src/components/Contentful/sass/sections/_our_services.scss

Moved overview bullet points left border colour styling to new_design_overrides. This is where the grid background colour is set, here we can specify that that the bullet points left border colour is set to white when the grid is black. This won't draw a border, because the border style is not yet specified (this needs to be done inside a custom class), meaning that generally bullet points won't have a left border.

Services overview bullet points left border

---

src/components/Contentful/sass/sections/_shared.scss

Adding a custom class 'overlay-title' to make h2 titles look like this:

Adding an overlay custom class for h2

---

src/components/Contentful/sass/base/_typography.scss

Previously: 
Now:
The Case Study page (https://www.madetech.com/case-study) requires a smaller (h1) title font size, as specified in Kalle's design. The Contentful Hero component already has a 'Text Size' option, and custom css class in the code base. This css class lives in the new_design script rather than _contentful_hero.scss - I am not sure if this means that other components might use this class to edit their h1. 
I edited the custom css class to reflect the necessary font sizes.

Hero title size custom class

---

src/components/Contentful/Grid.js

with the <a> tag display set to none, this actually broke the header link functionality. By setting the opacity to 0 however, the functionality remains, but the anchor is invisible. 
When visible:
With opacity at 0:

sets anchor link opacity to 0

---

src/components/Contentful/sass/abstracts/_variables.scss
src/components/Contentful/sass/base/_typography.scss
src/components/Contentful/sass/components/_contentful_hero.scss

Moved all Hero h1 styling from the hero CSS script to the typography CSS script as this was where initially the hero h1 styling was set, and for consistency I also placed the h1 small styling here too. 
Changed some of the styling as it didn't quite match the specifications set by Kalle in Zeplin. Also set appropriate values for the screen breakspoints. 
Before h1 small styling:
After:

Hero small title 

---

src/components/Contentful/Grid.js
src/components/Contentful/Hero.js
src/components/Contentful/Prose.js
src/components/Contentful/index.js
src/components/Contentful/sass/_new_design.scss
src/components/Contentful/sass/components/_contentful_prose.scss
src/components/Contentful/sass/sections/_our_purpose.scss
src/templates/ContentfulPage/index.js

This is a start to styling the [Our Purpose](https://www.madetech.com/our-purpose) page.
Main changes:
I've edited **Hero** so:
- You can choose if you want the image before the text
- You can change the image's shadow colour to be different from the colour of the title
From:
To:
I've also edited **Prose and GridProse** so that it can do overlays, mainly for the Our Purpose page, but also for other pages with overlay prose such as [Local Government](https://www.madetech.com/sectors/local-government):
**Our Purpose**
From:
To:
**Local Government**
From:
To:

Fixing purpose page

---

src/components/Contentful/sass/sections/_case_study_2.scss

Added styling to case-study-2 section to follow the updated design for tablet and mobile view ports. Also added some changes to the image so it properly fills its section on desktop view.
From:
To:
From:
To:
From:
To:

Case study 2

---

src/components/Contentful/Hero.js
src/components/Contentful/sass/_new_design.scss
src/components/Contentful/sass/components/_contentful_hero.scss
src/components/Contentful/sass/sections/_case_study_moj.scss

For this page: https://app.zeplin.io/project/5de03234a892f77c201cf303/screen/5de03456e1ccaf7baef2049c
First simple change, added a new scss file so I can style componenets in the page.
- Only thing so far was adding padding between the first big paragraph and the inline images.
- Need to add a lot more styling!
From:
To:
Then because this design requires a different style of Hero, I added an option to have 'none' as a Header Image Shadow Colour for Heros.
So now if you choose this, the image is rendered as an <img> tag rather than just the background-image of the div.
As background-image:
Now:
I had to also add a low-quality background-image to the <img> tag, so that there's lazy loading.

Case study - MoJ page

---

src/components/Contentful/sass/sections/_shared.scss

Added a custom class to change the small section title of case-study-1 and case-study-2 to match the design.
From:
To:

changes to case-study-1 and case-study-2

---

src/components/Contentful/sass/components/_new_design_overrides.scss
src/components/Contentful/sass/sections/_our_services.scss

Added more styling to overview-text and services-overview-bulletpoints sections for desktop view.
From:
To:
Also improved the styling for mobile view port, but it is still work in progress.
From:
To:
and

Services overview new

---

src/components/Contentful/sass/sections/_contact.scss

Trello: https://trello.com/c/prc7VMlA/173-career-promo-wrong-type-styling
- Correcting the size and weight of 'CAREERS' mini heading
- Correcting font size for the paragraph and links
- Making it all look okay on smaller viewports
From:
To:

Fixes for Kalles feedback about the careers section on contact page

---

src/components/Contentful/sass/components/_contentful_carousel.scss

Addressing this card: https://trello.com/c/Px53yR7A/229-case-study-should-this-be-a-carousel
Mainly making the carousel images the same height and width, because before each one was a  slightly different height, which made them look a bit funny.
Also chandging the :before content from '' to none, as that might be a bit clearer.

Carousel images

---

src/components/Contentful/Hero.js
src/components/Contentful/index.js
src/templates/ContentfulPage/index.js

Changing the text in Hero from short text to rich text in Contentful, so that it can be formatted according to the designs.
From:
To:

Hero update

---

src/components/Contentful/sass/components/_contentful_hero.scss
src/components/Contentful/sass/sections/_case_study_1.scss
src/components/Contentful/sass/sections/_case_study_2.scss
src/components/Contentful/sass/sections/_our_purpose.scss
src/components/Contentful/sass/sections/_our_services.scss

Aimed at the /our-purpose page.
Most of the prose was Montserrat, but corrected to Poppins.
But then had to change the font in the Case Study components back to Montserrat.
Also made the text responsive.
Added a little padding between these pictures for lg-tablet so it looks less crowded and reduced the gap between the images and captions
From:
To:

Vision fixes

---

src/components/Contentful/sass/_new_design.scss
src/components/Contentful/sass/sections/_case_study.scss

Now that we're duplicating the template case-study page, it makes sense to have these classnames be more generic for all case studies, and not just refer to MoJ and the sections on its page.

Moj custom class

---

src/components/Contentful/sass/components/_contentful_hero.scss

For some reason you need to add **display: inline-block** in order to add margins to links. See [this stackoverflow link](https://stackoverflow.com/questions/11969427/margin-bottom-for-a-link-elements): "Anchors do not accept width, height, margin etc until they are defined as block level or inline-block elements."
Before:
After:

Add margins to header links.

---

src/components/Contentful/MobileMenu.js
src/components/Contentful/sass/components/_contentful_mobile_menu.scss

Small PR, this gets rid of the slide-in transition for the mobile nav that you can see in staging at the moment.
Also moved the logo in the open menu up by 1px, as you could see that it wasn't _quite_ on top of the on in the header underneath!

Mobile nav

---

src/components/Contentful/Hero.js
src/components/Contentful/sass/components/_contentful_hero.scss

Previously I used display: inline-block to enable me to add margin to the header links. 
This caused some of the links to not have a line break between them:
Turns out that **inline-block** does not add a line-break after an element. But **block** does. See [link](https://www.w3schools.com/css/css_inline-block.asp)
Result:
Also removed the `<br>` tags in the JavaScript that were meant to be adding line-breaks after the links. Firstly, this didn't work. Secondly, apparently you should be using CSS margins/paddings to separate elements instead of `<br>` tags ([this person said so](https://www.sitepoint.com/community/t/br-drives-me-crazy/88910/3))

Change css display property

---

src/components/Contentful/sass/sections/_case_study_1.scss
src/components/Contentful/sass/sections/_case_study_2.scss
src/components/Contentful/sass/sections/_shared.scss

- Increased the font-weight of the 'Case Study' title - even though it was bold and typography was imported, it was incorrect. I entered an actual value to get the correct weight. 
- Decreased the font size of prose and links. There are two Case Study sections and each have their own style sheets. I edited both style sheets to set the font size. _Interestingly_ in Case Study 1 I only needed to set the font size in one place, but in Case Study 2 I had to do it in two places. That's because Case Study 2 is on a grid with a white background. The styling for the white grid overrode the font size, so I had to set it in another place as well. 
Before:
After:

Change fonts in case study section

---

src/components/Contentful/sass/sections/_academy.scss

The Academy stylesheet is a mess and this has probably added to that.
Mainly wanted to fix the overlay since that had gotten a bit messed us cause of changes elsewhere:
Also had other minor changes since we have the _actual_ photos, so the page had to be adjusted slightly:
Also felt that the font-size on mobile for regular text was a bit large, so shrunk that down a bit:

Academy fixes

---

src/components/Layout/Meta.js

Add `twitter:card` meta tag.
So that we can embed image links to our content on Twitter.
See here for more: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started
Test here: https://cards-dev.twitter.com/validator

Enable twitter card mode

---

config/nginx.conf.erb

Remove `location` block from the `rewrite` rule for `/services/ruby-on-rails-development`.
We went to test if the `location` block or the `last` made it work...

Remove location from the rewrite rule for RoR

---

src/helpers/documentToHtmlString.js
src/helpers/documentToHtmlString.test.js

Using an empty string for an image title would render "null" as the title, this change displays empty string

Allowing image title to show empty string not null

---

src/components/Contentful/DripForm.js
src/components/Contentful/DripForm.test.js

Having issues with not getting the prop information from contentful sometimes, this checks if vital props are missing and returns a null component in those situations to prevent an error message appearing on the site

Add check for missing props in Drip Form

---

src/components/Contentful/DripForm.js
src/components/Contentful/DripForm.test.js
src/templates/ContentfulPage/index.js

Updates the form with validation and dynamically generated HTML description.
Adds dripForm to the graphql query

Add drip form to content spread in graphql

---

config/nginx.conf.erb

Creating a permanent redirect for a temp academy page to the real one. This is to solve a problem that google indexed the page while building.

Redirect for temp to new academy page
